export const SHUT_DOWN = 'SHUT_DOWN';

export const START_BUTTON_CLICKED = 'START_BUTTON_CLICKED';
export const START_MENU_BLUR = 'START_MENU_BLUR';

export const OPEN_NOTEPAD = 'OPEN_NOTEPAD';
export const OPEN_ABOUT = 'OPEN_ABOUT';
export const OPEN_MODAL = 'OPEN_MODAL';

export const FOCUS_NOTEPAD = 'FOCUS_NOTEPAD';
export const FOCUS_ABOUT = 'FOCUS_ABOUT';

export const BLUR_NOTEPAD = 'BLUR_NOTEPAD';
export const BLUR_ABOUT = 'BLUR_ABOUT';

export const MINIMIZE_NOTEPAD = 'MINIMIZE_NOTEPAD';
export const MINIMIZE_ABOUT = 'MINIMIZE_ABOUT';

export const MAXIMIZE_NOTEPAD = 'MAXIMIZE_NOTEPAD';
export const MAXIMIZE_ABOUT = 'MAXIMIZE_ABOUT';

export const EXIT_NOTEPAD = 'EXIT_NOTEPAD';
export const EXIT_ABOUT = 'EXIT_ABOUT';
export const EXIT_MODAL = 'EXIT_MODAL';